#!/bin/bash

# Script to fix markdown headers generated by edown
# Removes unnecessary # symbols at the end of header lines

find doc -type f -name "*.md" -exec sed -i '' -E 's/ #+$//' {} \;

echo "Markdown headers fixed in all documentation files." 