# Kernel configuration file path
kernel_file: "/home/peterfarber/_Current/HyperBEAM/native/digest_calc/files/kernel"  # Path to the kernel binary

# Initrd configuration file path
initrd_file: "/home/peterfarber/_Current/HyperBEAM/native/digest_calc/files/initrd"  # Path to the initrd (initial RAM disk)

# OVMF (Open Virtual Machine Firmware) file path
ovmf_file: "/home/peterfarber/_Current/HyperBEAM/native/digest_calc/files/ovmf"  # Path to the OVMF file used for virtual machine boot

# Kernel command line arguments
cmdline: "console=ttyS0 earlyprintk=serial root=/dev/sda boot=verity verity_disk=/dev/sdb verity_roothash=7270de8ae229d0e8c219170b2c8b34d20d544d74f77c9469b81d22b1697ad3aa" 
# Kernel boot arguments including console settings, verity disk and root hash for secure boot

# Number of virtual CPUs to be allocated for the virtual machine
vcpus: 1  # Set to 1 for a single virtual CPU (adjust as necessary)

# VCPU Types: List of available virtual CPU models. These are typically based on physical CPU models.
# Each of these types corresponds to a specific configuration of CPU features that the virtual machine will use.
# Examples include specific features for hardware virtualization, optimizations, or security configurations.

vcpu_type: "EpycV4"  # Choose the CPU model for the virtual machine (EpycV4 is a modern AMD CPU type)

# Virtual Machine Monitor (VMM) Types: Specifies the hypervisor used for the VM.
# - QEMU: A generic and widely used open-source hypervisor.
# - EC2: Amazon's EC2 instance type for cloud-based VMs.
# - KRUN: A specialized hypervisor used in specific security and research contexts.
vmm_type: "QEMU"  # Choose the type of hypervisor. QEMU is commonly used for local virtual machines.

# Guest Features:
# The guest features are represented by individual bits in a 64-bit integer.
# Each bit in the 64-bit integer corresponds to an enabled or disabled feature for the virtual machine.
# The bits can be set to '1' to enable a specific feature, or '0' to disable it.

# Here's the breakdown of the available bits:

# | Bit | Feature              |
# |-----|----------------------|
# |  0  | SNPActive            |  # Enables Secure Nested Paging (SNP), enhancing security for the VM
# |  1  | vTOM                 |  # Enables virtual Trusted Opaque Memory, a security feature
# |  2  | ReflectVC            |  # Enables Reflection for VC (Virtualization Context)
# |  3  | RestrictedInjection  |  # Restricts certain types of injection into the VM
# |  4  | AlternateInjection   |  # Enables alternate forms of injection into the VM
# |  5  | DebugSwap            |  # Allows for debugging VM swap operations
# |  6  | PreventHostIBS       |  # Prevents Instruction-Based Sampling on the host system
# |  7  | BTBIsolation         |  # Isolates Branch Target Buffer for security
# |  8  | VmplSSS              |  # Enables Virtual Memory for Secure State (SSS) support
# |  9  | SecureTSC            |  # Enables Secure Time Stamp Counter, preventing time-based attacks
# | 10  | VmgexitParameter     |  # Enables parameters related to VM exit for performance tuning
# | 11  | Reserved, SBZ        |  # Reserved bit, should not be used, always zero
# | 12  | IbsVirtualization    |  # Allows Ibs (Interrupt-based Sampling) virtualization
# | 13  | Reserved, SBZ        |  # Reserved bit, should not be used, always zero
# | 14  | VmsaRegProt          |  # Enables VM-Sensitive Register Protection
# | 15  | SmtProtection        |  # Protects against Simultaneous Multithreading (SMT) attacks

# The value is represented as a hexadecimal string where each bit corresponds to a feature.
# For example, a value of "0000000000000001" means:
# - Bit 0 (SNPActive) is enabled.
# All other bits are set to 0.

guest_features: "0000000000000001"  # Bit 0: SNPActive Enabled (secure virtualization enabled)

# Notes:
# - You can adjust this value to enable or disable features by modifying the appropriate bits.
# - To turn on additional features, set the corresponding bit to '1' (e.g., "0000000000000011" to enable SNPActive and vTOM).
